// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxskctiwpiwlzkdihdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keHNrY3Rpd3Bpd2x6a2RpaGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQzNjMsImV4cCI6MjA2NzIyMDM2M30.82uM0hctk6qrgAqqxLkO6_IpYBeANAgL_5_gZv6BWy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});